### ISSUE TITLE
Enhancement: remove "unnecessary" dependencies

### ISSUE THREAD

**Issue by wadells** [ScottWales/puppet-reviewboard#2]
Hi Scott,

I've been fiddling with the code here, and would like to limit the dependencies of the module to only what is actually required by Review Board.

The first issue I was looking at is: we don't use epel at my employer (instead, we have our own repos that we mirror a subset of epel packages, along with our internal packages).

Similarly, I have no interest a hard dependency on puppetlabs-postgresql if we don't need it for our review board setup. We use mysql, and I don't want an unused dependency of this module to cause conflicts with other modules.  Admittedly low risk with a puppetlabs issued dependency, but still.

I understand the desire to keep this module as plug and play as possible, but I believe it will have broader out of the box useability and see greater adoption if it doesn't depend on as many modules.

Before forking and uploading a version of the puppet-reviewboard that meets my needs, I wanted to discuss with you, and see if you're open to trimming down on the dependencies.

Thoughts?

**Comment by ScottWales** [comment]
Hi Walt,

As you say the reason to include those dependencies is to have the module work out of the box. On the other hand I'd like it to be easy to swap out the database & web server. It would be nice if puppet could handle optional dependencies (looks like it's in the bug tracker - https://tickets.puppetlabs.com/browse/FORGE-91)

I think it's fairly safe to ask users to manually install the modules for things as large as the web server and DB, the EPEL dependency is only used for testing so that can be removed from the dependency list as well.

**Comment by ScottWales** [comment]
@javins I've removed the dependencies in master

Cheers, Scott

**Comment by wadells** [comment]
Thanks Scott!  I think https://tickets.puppetlabs.com/browse/FORGE-91 hit my nail on the head.

Hopefully the good documentation will make up for the lack of a hard dependency.

One possible solution for 'it works out of the box without lots of dependencies' would be to have the default setup be something not so production grade that has fewer dependences (e.g. the django's self hosting dev server & sqllite).  Then again, it may be better not to lead folks astray by having the out-of-the-box setup be generally shoddy.
